///////////////////////////////////////////////////////////
//  Controller.cs
//  Implementation of the Class Controller
//  Generated by Enterprise Architect
//  Created on:      22-2ÔÂ-2017 22:34:19
//  Original author: Doku
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ECharts.Entities {
	public class Controller {



        public VisualItem inRange
        {
			get;
			set;
		}

        public VisualItem outOfRange
        {
			get;
			set;
		}

        public VisualItem InRange()
        {
            if(this.inRange==null)
                this.inRange = new VisualItem();
            return this.inRange;
        }


        public VisualItem OutOfRange()
        {
            if (this.outOfRange == null)
                this.outOfRange = new VisualItem();
            return this.outOfRange;
        }

	    /// 
	    /// <param name="inRange"></param>
	    public Controller InRange(VisualItem inRange)
	    {
	        this.inRange = inRange;
	        return this;
	    }

	    /// 
		/// <param name="outOfRange"></param>
		public Controller OutOfRange(VisualItem outOfRange){
		     this.outOfRange=outOfRange;
		return this; 
		}

	}//end Controller

}//end namespace Entities